
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/main/NavBar";
import Drawer from "@/components/Drawer/main/Drawer";
import { DrawerProvider } from "@/context/DrawerContext";
import GlobalDrawer from "@/components/GlobalDrawer/main/GlobalDrawer";
import ReduxProvider from "@/Redux/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
    <GlobalDrawer/>
    
        <NavBar/>
 
        {children}
    
        </ReduxProvider>
    
      </body>
    </html>

  );
}
